package scheduler.dao;



import scheduler.helper.DBConnection;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import scheduler.model.Appointment;
import scheduler.model.Contacts;
import scheduler.model.Reports;
import java.sql.*;
import java.time.*;


public class AppointmentDao {

    /**
     * This method inserts an appointment into the MySQL database.
     *
     * @param appointment the appointment object containing details to be inserted into the database.
     * @return true if the appointment is successfully inserted. False if not.
     * @throws SQLException if an error occurs while inserting an appointment.
     */
    public boolean addAppointment(Appointment appointment) throws SQLException {

        String insertAppointment = "INSERT INTO appointments(Title, Description, Location, Contact_ID, Type, Start, End, Customer_ID, User_ID) VALUES (?,?,?,?,?,?,?,?,?)";
        try (PreparedStatement insertSqlStatement = DBConnection.getConnection().prepareStatement(insertAppointment, PreparedStatement.RETURN_GENERATED_KEYS)) {
            insertSqlStatement.setString(1, appointment.getTitle());
            insertSqlStatement.setString(2, appointment.getDescription());
            insertSqlStatement.setString(3, appointment.getLocation());
            insertSqlStatement.setInt(4, appointment.getContacts().getContactID());
            insertSqlStatement.setString(5, appointment.getType());
            insertSqlStatement.setTimestamp(6, Timestamp.valueOf(appointment.getStart()));
            insertSqlStatement.setTimestamp(7, Timestamp.valueOf(appointment.getEnd()));
            insertSqlStatement.setInt(8, appointment.getCustomerID());
            insertSqlStatement.setInt(9, appointment.getUserID());

            int appointmentInserted = insertSqlStatement.executeUpdate();

            if (appointmentInserted == 1) {
                try (ResultSet autoGeneratedID = insertSqlStatement.getGeneratedKeys()) {
                    if (autoGeneratedID.next()) {
                        int appointmentID = autoGeneratedID.getInt(1);
                        appointment.setAppointmentID(appointmentID);
                    }
                }
                return true;
            }
        } catch (SQLException e) {
            System.err.println("Error inserting appointment" + e.getMessage());
            return false;
        }
        return false;
    }

    /**
     * This Method retrieves all the appointments from the MySQL database.
     * Appointments are displayed in the user's system default time zone.
     *
     * @return an ObservableList containing all the appointments in the database.
     * @throws SQLException if an error occurs while retrieving the appointments.
     */
    public static ObservableList<Appointment> getAllAppointments() throws SQLException {
        ObservableList<Appointment> appointmentObservableList = FXCollections.observableArrayList();
        System.out.println("Retrieving all appointments");

        String sql = """
        SELECT a.Appointment_ID, a.Title, a.Description, a.Location, a.Type, a.Start, a.End,
               a.Customer_ID, a.User_ID, c.Contact_ID, c.Contact_Name, c.Email
        FROM appointments AS a
        JOIN contacts AS c ON a.Contact_ID = c.Contact_ID
        """;
        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {

                int appointmentID = resultSet.getInt("Appointment_ID");
                String title = resultSet.getString("Title");
                String description = resultSet.getString("Description");
                String location = resultSet.getString("Location");
                String type = resultSet.getString("Type");

                //Get UTC times from the database
                LocalDateTime start = resultSet.getTimestamp("Start").toLocalDateTime();
                LocalDateTime end = resultSet.getTimestamp("End").toLocalDateTime();

                //Converts UTC times to local time
//                LocalDateTime startLocal = TimeConversions.toLocalTime(startUTC);
//                LocalDateTime endLocal = TimeConversions.toLocalTime(endUTC);

                int customerID = resultSet.getInt("Customer_ID");
                int userID = resultSet.getInt("User_ID");

                int contactID = resultSet.getInt("Contact_ID");
                String contactName = resultSet.getString("Contact_Name");
                String email = resultSet.getString("Email");

                Contacts contacts = new Contacts(contactID, contactName, email);

                Appointment appointment = new Appointment(appointmentID, title, description, location, contacts, type, start, end, customerID, userID);

                appointmentObservableList.add(appointment);
            }
        } catch (SQLException e) {
            System.err.println("ERROR getting all appointments" + e.getMessage());
            throw e;
        }
        return appointmentObservableList;
    }

    /**
     * This method updates an appointment in the MySQL database.
     *
     * @param appointment the appointment object containing updated details to be saved to the database.
     * @return true if the appointment is successfully updated. False if not.
     * @throws SQLException if a database error occurs while updating the appointment.
     */
    public boolean update(Appointment appointment) throws SQLException {
        boolean updated;

        String updateAppointment = "UPDATE appointments SET Title = ?, Description = ?, Location = ?,Contact_ID = ?, Type = ?, Start = ?, End = ?, Customer_ID = ?, User_ID = ? WHERE Appointment_ID = ?";
        try(PreparedStatement updateSqlStatement = DBConnection.getConnection().prepareStatement(updateAppointment)) {

            updateSqlStatement.setString(1, appointment.getTitle());
            updateSqlStatement.setString(2, appointment.getDescription());
            updateSqlStatement.setString(3, appointment.getLocation());
            updateSqlStatement.setInt(4, appointment.getContacts().getContactID());
            updateSqlStatement.setString(5, appointment.getType());
            updateSqlStatement.setTimestamp(6, Timestamp.valueOf(appointment.getStart()));
            updateSqlStatement.setTimestamp(7, Timestamp.valueOf(appointment.getEnd()));
            updateSqlStatement.setInt(8, appointment.getCustomerID());
            updateSqlStatement.setInt(9, appointment.getUserID());
            updateSqlStatement.setInt(10, appointment.getAppointmentID());

            updateSqlStatement.executeUpdate();
            updated = true;

        } catch (SQLException e) {
        System.err.println("Error updating appointment:"+e.getMessage());
        updated = false;
    }
        return updated;
    }

    /**
     * This Method deletes an appointment from the MySQL database if it matches the Appointment_ID.
     *
     * @param appointment the appointment object being deleted.
     * @return true if successfully deleted. False if not.
     */
    public static boolean delete(Appointment appointment){

        String sql= "DELETE FROM appointments WHERE Appointment_ID = ?";
        boolean deleted = false;

        try (PreparedStatement deleteSqlStatement = DBConnection.getConnection().prepareStatement(sql)) {
            deleteSqlStatement.setInt(1, appointment.getAppointmentID());
            deleteSqlStatement.executeUpdate();
            deleted = true;
        } catch (SQLException e) {
            System.err.println("Error deleting appointment:"+e.getMessage());
        }
        return deleted;
    }

    /**
     * Retrieves an appointment from a ResultSet.
     *
     * @param resultSet the ResultSet containing the appointment data.
     * @return an appointment object populated with the data from the ResultSet.
     * @throws SQLException if an error occurs while retrieving the appointment from the database.
     */
    public static Appointment retrieveAppointmentsFromResultSet(ResultSet resultSet) throws SQLException {

       int appointmentID = resultSet.getInt("Appointment_ID");
        String title = resultSet.getString("Title");
        String description = resultSet.getString("Description");
        String location =  resultSet.getString("Location");
        String type = resultSet.getString("Type");
        LocalDateTime start = resultSet.getTimestamp("Start").toLocalDateTime();
        LocalDateTime end = resultSet.getTimestamp("End").toLocalDateTime();
        int customerID = resultSet.getInt("Customer_ID");
        int userID = resultSet.getInt("User_ID");

        int contactID = resultSet.getInt("Contact_ID");
        String contactName = resultSet.getString("Contact_Name");
        String email = resultSet.getString("Email");
        Contacts contacts = new Contacts(contactID, contactName, email);

        return new Appointment(appointmentID, title, description, location, contacts, type, start, end, customerID, userID);
    }


    /**
     * Retrieves all appointments for the current month from the database.
     *
     * @return an ObservableList containing all appointments for the current month.
     * @throws SQLException if an error occurs while retrieving appointments from the database.
     */
    public static ObservableList<Appointment> getMonthlyAppointments() throws SQLException {
        ObservableList<Appointment> appointmentObservableList = FXCollections.observableArrayList();
        String sql = "SELECT a.*, c.Contact_Name, c.Email FROM appointments a JOIN contacts c ON a.contact_ID = c.contact_ID WHERE MONTH(a.Start) = MONTH(CURRENT_DATE()) AND YEAR(a.Start) = YEAR(CURRENT_DATE())";

        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                Appointment appointment = retrieveAppointmentsFromResultSet(resultSet);
                String contactName = resultSet.getString("Contact_Name");
                String email = resultSet.getString("Email");
                appointment.getContacts().setContactName(contactName);
                appointmentObservableList.add(appointment);
            }
        }
        return appointmentObservableList;
    }

    /**
     * Retrieves all appointments for the current week from the database.
     *
     * @return an ObservableList containing all appointments for the current week.
     * @throws SQLException if an error occurs while retrieving appointments from the database.
     */
    public static ObservableList<Appointment> getWeeklyAppointments() throws SQLException {
        ObservableList<Appointment> appointmentObservableList = FXCollections.observableArrayList();
        String sql = "SELECT a.*, c.Contact_Name, c.Email FROM appointments a JOIN contacts c ON a.Contact_ID = c.Contact_ID WHERE YEARWEEK(a.Start, 1)= YEARWEEK(CURRENT_DATE(), 1)";

        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                Appointment appointment = retrieveAppointmentsFromResultSet(resultSet);
                String contactName = resultSet.getString("Contact_Name");
                String email = resultSet.getString("Email");
                appointment.getContacts().setContactName(contactName);
                appointmentObservableList.add(appointment);
            }
        }
        return appointmentObservableList;
    }


    /**
     * Retrieves all appointments for a specific customer based on their Customer_ID.
     *
     * @param customerID the Customer_ID to filter appointments.
     * @return an ObservableList containing all appointments for the specified customer.
     */
    public static ObservableList<Appointment>getAppointmentsByCustomer(int customerID) {
       ObservableList<Appointment> appointments = FXCollections.observableArrayList();

       String sql = "SELECT * FROM appointments WHERE Customer_ID = ?";

       try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
           statement.setInt(1, customerID);
           ResultSet resultSet = statement.executeQuery();

           while (resultSet.next()) {
               int appointmentID = resultSet.getInt("Appointment_ID");
               String title = resultSet.getString("Title");
               String description = resultSet.getString("Description");
               String location =  resultSet.getString("Location");
               int contactID = resultSet.getInt("Contact_ID");
               String type = resultSet.getString("Type");
               LocalDateTime start = resultSet.getTimestamp("Start").toLocalDateTime();
               LocalDateTime end = resultSet.getTimestamp("End").toLocalDateTime();
               int userID = resultSet.getInt("User_ID");

               Contacts contacts = ContactsDao.getContactByID(contactID);

               Appointment appointment = new Appointment(appointmentID, title, description, location, contacts, type, start, end, customerID, userID);
               appointments.add(appointment);
           }
       } catch (SQLException e) {
           System.err.println("Error retrieving appointments by Customer ID:"+e.getMessage());
       }

        return appointments;
    }

    /**
     * Retrieves all appointments by type from the database.
     *
     * @return an ObservableList containing appointment types and totals.
     */
    public static ObservableList<Appointment> getAppointmentsByType() {
        ObservableList<Appointment> appointmentsByType = FXCollections.observableArrayList();
        String sql = "SELECT Type, COUNT(*) as Total From appointments GROUP BY Type";

        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                String type = resultSet.getString("Type");
                int total = resultSet.getInt("Total");
                appointmentsByType.add(new Appointment(total,type));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return appointmentsByType;
    }

    /**
     * Retrieves all appointments by month from the database.
     *
     * @return an ObservableList containing the total number of appointments per month.
     */
    public static ObservableList<Reports> getAppointmentsByMonth() {
        ObservableList<Reports> appointmentsByMonth = FXCollections.observableArrayList();
        String sql = "SELECT MONTH(Start) as Month, COUNT(*) as Total From appointments GROUP BY Month(Start)";

        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                int monthNumber = resultSet.getInt("Month");
                String reportMonth = Month.of(monthNumber).name();
                int total = resultSet.getInt("Total");

                appointmentsByMonth.add(new Reports(total, reportMonth));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return appointmentsByMonth;
    }

    /**
     * Retrieves the schedule of appointments for a specific contact based on their Contact_ID.
     *
     * @param contactID the Contact_ID to filter appointments by.
     * @return an ObservableList containing all the appointments for the specific contact.
     * @throws SQLException if an error occurs while retrieving the contacts schedule from the database.
     */
    public static ObservableList<Appointment> getContactsSchedule(int contactID) throws SQLException {
        ObservableList<Appointment> contactsSchedule = FXCollections.observableArrayList();
        String sql = "SELECT * FROM appointments WHERE Contact_ID = ?";

        try (PreparedStatement statement = DBConnection.getConnection().prepareStatement(sql)) {
            statement.setInt(1, contactID);
            ResultSet resultSet = statement.executeQuery();
            while (resultSet.next()) {
                int appointmentID = resultSet.getInt("Appointment_ID");
                String title = resultSet.getString("Title");
                String description = resultSet.getString("Description");
                String type = resultSet.getString("Type");
                LocalDateTime start = resultSet.getTimestamp("Start").toLocalDateTime();
                LocalDateTime end = resultSet.getTimestamp("End").toLocalDateTime();
                int customerID = resultSet.getInt("Customer_ID");

                contactsSchedule.add(new Appointment(appointmentID, title, description, type, start, end, customerID));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return contactsSchedule;
    }

}
